server:
    port: 80
spring:
    datasource:
        password: ENC(idmv4Ls2v/SJuyrTr2ciXpe3EnHD6xMB)
        url: ENC(a1AH1KSHR1VhqaSos/bq8Uqr789wsnZP5rOqCKLis5Za1wCamj6w+soJv/bCG+OCJnlbpYem0aiZ9JB9wk8ZmKd4Izrn1sQ2A6+s4T3kFQ4s8uEYGjUZVoMbTw3vJsqnMDon825YbtF2z9SBC6at0GJFyGvCHJdfLCV4wT+LdD105k2mxEyOQQ==)
        username: ENC(x+jHhMgYPxGqO5JzP1HfoQ==)
    redis:
        password: ENC(b1WryJFdS/CwhXhg/Jhi3wvfOLPKBN9/)
    application:
        name: my7un-main
aliyun:
  accessKeyId: ENC(6cQIy9IcCYRzjnNQQKvpAeyUA79hwu/GIUwXKNKm/HwVh/KgSSe0mw==) #6cQIy9IcCYRzjnNQQKvpAeyUA79hwu/GIUwXKNKm/HwVh/KgSSe0mw==
  secret: ENC(EPMfXiUUNaSrQhve37oaljQRRJjgOuDXxq/HJIvz0MjG4ierV/G3XA==)  #EPMfXiUUNaSrQhve37oaljQRRJjgOuDXxq/HJIvz0MjG4ierV/G3XA==
  endpoint: i7unoss.top
  #endpoint: oss-cn-beijing-internal.aliyuncs.com

#eureka:
#  client::
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#feign:
#  hystrix:
#    enabled: true