server:
    port: 80
spring:
    datasource:
        password: user_dbpass
        url: jdbc:mysql://rm-2zev83tvb4y3n75ht125010.mysql.rds.aliyuncs.com/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: user_db
    redis:
        password: redispass
    application:
        name: my7un-main
aliyun:
  accessKeyId: LTAI4G4jgTN2fmeCEpWo3xfw
  secret: klNd8NRAl0ocQZ9u12xgo2pPcDCJB1
  endpoint: oss-cn-beijing-internal.aliyuncs.com

#eureka:
#  client::
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#feign:
#  hystrix:
#    enabled: true