server:
    port: 80
spring:
    datasource:
        password: 12345678
        url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
    redis:
        password: ''
    application:
        name: my7un-main
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#feign:
#  hystrix:
#    enabled: true