server:
    port: 80
spring:
    datasource:
        password: 12345678
        url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
    redis:
        password: ''
    application:
        name: my7un-main
aliyun:
  accessKeyId: ENC(6cQIy9IcCYRzjnNQQKvpAeyUA79hwu/GIUwXKNKm/HwVh/KgSSe0mw==) #6cQIy9IcCYRzjnNQQKvpAeyUA79hwu/GIUwXKNKm/HwVh/KgSSe0mw==
  secret: ENC(EPMfXiUUNaSrQhve37oaljQRRJjgOuDXxq/HJIvz0MjG4ierV/G3XA==)  #EPMfXiUUNaSrQhve37oaljQRRJjgOuDXxq/HJIvz0MjG4ierV/G3XA==
  endpoint: ENC(8foE8aG4uvaIoSnNxAQkSDStz3gvCTVUCPctqRQuUduHncLYhFDtYQ==)

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#feign:
#  hystrix:
#    enabled: true