server:
  port: 5000
spring:
  application:
    name: my7un-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    my7un:
      path: /my7un/**
      serviceId: my7un-main